### ISSUE TITLE
Only three lines for the anwser

### ISSUE THREAD

**Issue by michelmorinmontreal** [Bavarder/Bavarder#38] opened 2023-06-17 13:31 UTC
The application only propose incomplete answer, on two or three lines.

On Linux Mint, from the depot (Application / Software manager)

![Screen](https://github.com/Bavarder/Bavarder/assets/136906204/b8663666-880d-4fbe-a9db-c94aa77868f5)

**Comment by 0xMRTT** [comment] 2023-06-17 15:17
try using another provider 

duplicate of #34

**Closed** 2023-06-17 15:17 UTC
