### ISSUE TITLE
Hugging Chat Infinite loading spinner

### ISSUE THREAD

**Issue by CaptainMorgan12** [Bavarder/Bavarder#20] opened 2023-05-06 16:50 UTC
Environment: mobile L5 phone, wayland, gtk, gnome3.38, bavarder v0.1.6, flatpak install, pureos10.

Steps to repeat:
1. in reply field enter question or textr and submit
2. go back to reply field and in next line enter question and submit
3. quickly keep doing 1-2, repeatedly or roughly about 6-8 times using different text

Observe the spinner shows constant loading and no more user interaction can be achieved. App has to be closed and reopened for it to work again. Changing chat provider doesnt remove the loading fault.

At a minimum what it should be doing is cancel all processes that are running or havent finished when switching chat provider. Additionally a failsafe option maybe good where timeout is reached if there is no communication from chat after say 3min it cancels ongoing request. Also maybe additionally asynchronous send receive would be a good feature because then a response that may take an hour to be received would still be received whioe user is doing other things.

Screenshot: 
![bavarder](https://user-images.githubusercontent.com/80182265/236636565-03e17658-7ba8-4597-8ebe-db6ba8b87280.png)

Debug
`{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
['baichat', 'catgpt', 'huggingchat', 'openaigpt35turbo', 'openaigpt4']
Loading provider baichat
Loading provider catgpt
Loading provider huggingchat
Loading provider openaigpt35turbo
Loading provider openaigpt4
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}
huggingchat
Setting selected provider to 2
{0: <bavarder.provider.baichat.BAIChatProvider object at 0xffffb0043880>, 1: <bavarder.provider.catgpt.CatGPTProvider object at 0xffffa5ab30a0>, 2: <bavarder.provider.huggingchat.HuggingChatProvider object at 0xffffa5ab30d0>, 3: <bavarder.provider.openaigpt35turbo.OpenAIGPT35TurboProvider object at 0xffffa5ab3d60>, 4: <bavarder.provider.openaigpt4.OpenAIGPT4Provider object at 0xffffa5ab3dc0>}
Saving providers data...
{'baichat': '{}', 'catgpt': '{}', 'huggingchat': '{}', 'openaigpt35turbo': '{"api_key": null}', 'openaigpt4': '{"api_key": null}'}`

**Comment by 0xMRTT** [comment] 2023-05-06 17:02
Which version are you using ?

**Comment by CaptainMorgan12** [comment] 2023-05-06 17:03
0.1.6

**Comment by 0xMRTT** [comment] 2023-05-06 17:07
The issue is with hgchat

**Comment by CaptainMorgan12** [comment] 2023-05-06 17:12
> The issue is with hgchat (the python lib)

is that something that need to be fixed upstream then? not sure i know enough about the library to file a bug report..

**Comment by 0xMRTT** [comment] 2023-05-06 17:15
THe library is part of Bavarder https://github.com/Bavarder/hgchat

**Comment by 0xMRTT** [comment] 2023-05-06 17:15
But the issue is strange because it's happen randomly

**Comment by CaptainMorgan12** [comment] 2023-05-06 19:50
is there a way to run bavarder with more debug symbols enabled? e.g. "-d" i wonder if its a connectivity issue with the server

**Comment by 0xMRTT** [comment] 2023-05-06 20:06
The issue is because sometimes json fails to decode a chunk which causes the app to load forever. I fixed that. And added more output to the user when the request fail. I'm going to release soon. (In the wait you can try github actions and tell me if the issue persist)

Thanks for the report

**Comment by MohammadsM** [comment] 2023-05-07 02:32
Hi
I had same problem with "Hugging Chat", But now it's working smoothly with version '0.1.6'.
Thank you 😘

**Comment by 0xMRTT** [comment] 2023-05-07 07:46
You are welcome. I'm going to release a new fix today

**Comment by 0xMRTT** [comment] 2023-05-07 14:29
0.1.7 has been released :rocket:

**Comment by CaptainMorgan12** [comment] 2023-05-07 20:45
Heyy @0xMRTT I realized the issue exists and is the same for any AI provider when you submit `<null>`, so no text. Then only restart helps.

Was that something supposed to be fixed in 0.1.7 or is that a roadmap item? (Greying out submit button when no text exists)

**Comment by 0xMRTT** [comment] 2023-05-07 20:51
Oh got it

**Comment by 0xMRTT** [comment] 2023-05-07 21:00
@CaptainMorgan12 now it should be fixed :)

You can try by using this build https://github.com/Bavarder/Bavarder/actions/runs/4909260265/jobs/8765559745

**Comment by CaptainMorgan12** [comment] 2023-05-07 21:06
> @CaptainMorgan12 now it should be fixed :)
> 
> You can try by using this build https://github.com/Bavarder/Bavarder/actions/runs/4909260265/jobs/8765559745

Awesome i give it a spin, no pun intended!

**Comment by DraconicNEO** [comment] 2023-05-15 17:52
I've been getting the same thing but there's no text output at all, just an infinite loading spinner on all AI models

**Comment by 0xMRTT** [comment] 2023-05-15 18:54
Did you updated to the latest version?

**Comment by 0xMRTT** [comment] 2023-05-15 18:57
Did you updated to the latest version?

**Comment by DraconicNEO** [comment] 2023-05-15 19:31
> Did you updated to the latest version?

Yes I installed from Flathub.

**Comment by 0xMRTT** [comment] 2023-05-15 20:26
Can you run it from the CLI using `flatpak run io.github.Bavarder.Bavarder` and send me the output

**Comment by MohammadsM** [comment] 2023-05-16 14:17
It seems that happened again in the new version. I just ran the `flatpak update` successfully.
Here is the log:
![Bildschirmfoto vom 2023-05-16 07-01-24](https://github.com/Bavarder/Bavarder/assets/4475328/471fa562-0f76-4d5a-ae76-5c9411e8ce55)

**Comment by 0xMRTT** [comment] 2023-05-16 14:27
Got it. It's because hugging chat now requires an account :/

**Comment by 0xMRTT** [comment] 2023-07-19 18:12
Next release will fix that

**Closed** 2023-08-27 16:18 UTC
